buildCount: 528
compileFiles:
- startup.lua
- system/bootloader.lua
- system/rel
- system/krnl.lua
- system/apis/arc.lua
- system/apis/col.lua
- system/apis/files.lua
- system/apis/hashing.lua
- system/apis/rd.lua
- system/apis/tutils.lua
- system/apis/ui.lua
- system/apis/window.lua
- system/apis/keys.lua
- services/arcfix.lua
- services/elevator.lua
- services/elevatorSrv.lua
- services/oobe.lua
- services/pms.lua
- services/shell.lua
- services/enabled/9 arcfix
- services/enabled/login
- data/PRIVACY.txt
- config/aboot
- config/arcrepo
- config/arcshell
- config/hostname
- config/passwd
- apps/adduser.lua
- apps/arc.lua
- apps/cat.lua
- apps/cd.lua
- apps/cp.lua
- apps/init.lua
- apps/kmsg.lua
- apps/ls.lua
- apps/mkdir.lua
- apps/mv.lua
- apps/rm.lua
- apps/rmuser.lua
- apps/shell.lua
- apps/uitest.lua
- apps/clear.lua
- apps/shutdown.lua
- apps/reboot.lua
- apps/celluitest.lua
mkDirs:
- system
- user
- temporary
- services
- data
- config
- apps
- apis
- system/apis
- services/enabled
- config/apps
nrFiles:
- services/enabled/login
- config/passwd
- config/aboot
- config/arcshell
- config/arcrepo
options:
- enableCompatibility
