options:
  - enableCompatibility
mkDirs:
  - system
  - system/apis
  - services
  - services/enabled
  - temporary
  - user
  - apps
  - apis
  - config
  - config/apps
  - data
compileFiles:
  - system/bootloader.lua
  - system/krnl.lua
  - system/installer.lua
  - system/liveinst.lua
  - system/devinstaller.lua
  - system/apis/col.lua
  - system/apis/rd.lua
  - system/apis/files.lua
  - system/apis/tutils.lua
  - system/apis/ui.lua
  - system/apis/arc.lua
  - system/apis/hashing.lua
  - services/arcfix.lua
  - services/elevator.lua
  - services/elevatorStep.lua
  - services/elevatorSrv.lua
  - services/shell.lua
  - services/pms.lua
  - services/oobe.lua
  - apps/init.lua
  - apps/shell.lua
  - apps/cd.lua
  - apps/ls.lua
  - apps/mv.lua
  - apps/cp.lua
  - apps/cat.lua
  - apps/rm.lua
  - apps/mkdir.lua
  - apps/uitest.lua
  - apps/kmsg.lua
  - apps/arc.lua
  - apps/adduser.lua
  - apps/rmuser.lua
  - startup.lua
nrFiles:
  - services/enabled/9 arcfix
  - services/enabled/login
  - config/passwd
  - config/aboot
  - config/arcshell
  - config/arcrepo
  # - config/hostname
